layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

  permalink: /:year/:month/:day/:title/

  defaults:
    -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
      values:
        layout: "post"

        projects:
          sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

  topics:
    - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/laravel/laravel.png

    - name: Vue.js
    web_url: https://github.com/topics/vuejs
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/vue/vue.png

    - name: Magento
    web_url: https://github.com/topics/magento
    image_url: 

    - name: Web design

    - name: Less
    web_url: https://github.com/topics/less
    image_url: https://raw.githubusercontent.com/github/explore/3783a65676ba479267fec803885f070760fee4ac/topics/less/less.png
    - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
